//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicJournal.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int idSchedule { get; set; }
        public Nullable<int> idClass { get; set; }
        public string day { get; set; }
        public Nullable<int> idTeacher { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
